# Generated by Django 4.2.7 on 2023-11-10 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_dispositif_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositif',
            name='users',
        ),
        migrations.CreateModel(
            name='UserDispositif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=4)),
                ('dispositif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.dispositif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'dispositif', 'code')},
            },
        ),
    ]
