# Generated by Django 4.2.7 on 2023-11-10 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_dispositif_users_userdispositif'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdispositif',
            unique_together=set(),
        ),
    ]
