# Generated by Django 4.2.7 on 2023-11-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_userdispositif_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdispositif',
            name='localisation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
