# Generated by Django 4.2.7 on 2023-11-11 12:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userdispositif_localisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonneeCapteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('date_heure', models.DateTimeField(default=datetime.datetime.now)),
                ('user_dispositif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userdispositif')),
            ],
        ),
    ]
